# Header
menu:
  Home: /
  Archives: /archives
  GitHub: https://github.com/vingojw
  Blog: http://www.jiweiwei.com
  util: /util
  ♬: /2014/10/11/find/

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:
  主题作者: http://xiguabaobao.com
  Mr.Peng: http://www.peng8.net
  微读时光: http://www.wdtime.cn/
  蒹葭从风: http://iu2fish.github.io/
  CSS小工具（林小志）:  http://linxz.github.io/tianyizone/


# Miscellaneous
google_analytics:  
favicon:
twitter: vingojw
google_plus:  
fb_admins:  
fb_app_id:

# Duoshuo
duoshuo_shortname: vingojw

# Baidu share
baidushare: true